name: github-secrets
on: push

jobs:
  deploy:
    name: Create an RDS instance
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials for the dummy account (Sandbox)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::975216159326:role/S3Admin
        aws-region: us-east-1

    - name: Create an RDS instance
      run: |
	aws rds create-db-instance --db-instance-identifier test-mysql --db-instance-class db.t3.micro --engine mysql --master-username admin 
--master-user-password mysecret --allocated-storage 20
